<?php

use App\Models\Supply;
use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;
use App\Models\User;

class CreateSuppliesTableAndInsertInitialData  extends Migration
{
    public function up()
    {
        Schema::create('supplies', function (Blueprint $table) {
            $table->id();
            $table->enum('type', ['PF', 'PJ'])->default('PF');
            $table->string('name', 255);
            $table->string('social_name', 255)->nullable();
            $table->string('cpf', 14)->nullable();
            $table->string('cnpj', 18)->nullable();
            $table->string('phone', 20);
            $table->string('cep', 9);
            $table->string('address', 255);
            $table->string('address_number', 20);
            $table->string('state', 2);
            $table->string('city', 100);
            $table->timestamps();
        });

        User::create([
            'name'     => 'Revenda Mais',
            'email'    => 'teste@revendamais.com.br',
            'password' => 'teste123'
        ]);

        foreach($this->supplyData as $supply) {
            Supply::create($supply);
        }
    }

    public function down()
    {
        Schema::dropIfExists('supplies');
    }

    public $supplyData = [
        [
            'type' => 'PJ',
            'name' => 'Peixoto',
            'cpf' => '',
            'cnpj' => '04.732.658/0001-49',
            'phone' => '+55 11 8242-1948',
            'cep' => '41157815',
            'address' => 'Largo Larissa da Rocha',
            'address_number' => '977',
            'state' => 'GO',
            'city' => 'Vieira',
        ],
        [
            'type' => 'PJ',
            'name' => 'Carvalho e Filhos',
            'cpf' => '',
            'cnpj' => '60.792.153/0001-40',
            'phone' => '+55 (084) 3933 2871',
            'cep' => '58714841',
            'address' => 'Loteamento de Viana',
            'address_number' => '99',
            'state' => 'RJ',
            'city' => 'Pires de Minas',
        ],
        [
            'type' => 'PF',
            'name' => 'Yasmin Nogueira',
            'cpf' => '534.169.027-34',
            'cnpj' => '',
            'phone' => '(071) 1122-0186',
            'cep' => '83396-947',
            'address' => 'Viaduto Luna Moraes',
            'address_number' => '6',
            'state' => 'RN',
            'city' => 'Rodrigues',
        ],
        [
            'type' => 'PJ',
            'name' => 'da Mota',
            'cpf' => '',
            'cnpj' => '30.485.126/0001-64',
            'phone' => '(071) 6012 3098',
            'cep' => '01399161',
            'address' => 'Condomínio Breno Aragão',
            'address_number' => '22',
            'state' => 'PR',
            'city' => 'Caldeira',
        ],
        [
            'type' => 'PJ',
            'name' => 'Viana - ME',
            'cpf' => '',
            'cnpj' => '91.408.625/0001-42',
            'phone' => '(021) 2087-0916',
            'cep' => '45792302',
            'address' => 'Loteamento Souza',
            'address_number' => '81',
            'state' => 'RO',
            'city' => 'Alves',
        ],
        [
            'type' => 'PJ',
            'name' => 'Oliveira',
            'cpf' => '',
            'cnpj' => '98.452.360/0001-29',
            'phone' => '84 0715-0842',
            'cep' => '75945992',
            'address' => 'Lagoa de Nogueira',
            'address_number' => '11',
            'state' => 'RN',
            'city' => 'Melo',
        ],
        [
            'type' => 'PJ',
            'name' => 'Duarte das Neves e Filhos',
            'cpf' => '',
            'cnpj' => '76.803.452/0001-73',
            'phone' => '+55 (061) 2714 2787',
            'cep' => '07547063',
            'address' => 'Vereda de Cardoso',
            'address_number' => '70',
            'state' => 'RO',
            'city' => 'Lopes do Sul',
        ],
        [
            'type' => 'PJ',
            'name' => 'Alves Almeida e Filhos',
            'cpf' => '',
            'cnpj' => '81.304.925/0001-28',
            'phone' => '+55 (061) 1761-0471',
            'cep' => '28512-400',
            'address' => 'Favela Ferreira',
            'address_number' => '155',
            'state' => 'SC',
            'city' => 'Ramos de Pinto',
        ],
        [
            'type' => 'PJ',
            'name' => 'Teixeira',
            'cpf' => '',
            'cnpj' => '23.649.017/0001-70',
            'phone' => '+55 81 5551-5900',
            'cep' => '22945-682',
            'address' => 'Condomínio Bárbara Duarte',
            'address_number' => '5',
            'state' => 'CE',
            'city' => 'Jesus',
        ],
        [
            'type' => 'PF',
            'name' => 'Helena Jesus',
            'cpf' => '618.435.270-90',
            'cnpj' => '',
            'phone' => '(081) 1760-4522',
            'cep' => '11133-060',
            'address' => 'Passarela Silveira',
            'address_number' => '87',
            'state' => 'SE',
            'city' => 'Pereira',
        ],
        [
            'type' => 'PF',
            'name' => 'João Lucas das Neves',
            'cpf' => '426.180.953-24',
            'cnpj' => '',
            'phone' => '51 7317 6430',
            'cep' => '92137658',
            'address' => 'Colônia Rodrigues',
            'address_number' => '79',
            'state' => 'RS',
            'city' => 'Silveira do Amparo',
        ],
        [
            'type' => 'PJ',
            'name' => 'Sales',
            'cpf' => '',
            'cnpj' => '73.802.546/0001-30',
            'phone' => '51 2492 6947',
            'cep' => '18013204',
            'address' => 'Praia Melo',
            'address_number' => '82',
            'state' => 'MS',
            'city' => 'Souza do Galho',
        ],
        [
            'type' => 'PF',
            'name' => 'Murilo Carvalho',
            'cpf' => '816.792.354-19',
            'cnpj' => '',
            'phone' => '0500-930-0248',
            'cep' => '51744-666',
            'address' => 'Esplanada Costela',
            'address_number' => '64',
            'state' => 'AL',
            'city' => 'Rocha',
        ],
        [
            'type' => 'PF',
            'name' => 'Bianca Rodrigues',
            'cpf' => '912.673.058-86',
            'cnpj' => '',
            'phone' => '51 7017 2009',
            'cep' => '51853671',
            'address' => 'Vale Rezende',
            'address_number' => '551',
            'state' => 'SE',
            'city' => 'Nogueira',
        ],
        [
            'type' => 'PJ',
            'name' => 'Costa',
            'cpf' => '',
            'cnpj' => '83.069.527/0001-08',
            'phone' => '(051) 5100-7408',
            'cep' => '31886841',
            'address' => 'Praça Pereira',
            'address_number' => '2',
            'state' => 'PA',
            'city' => 'Castro',
        ],
        [
            'type' => 'PF',
            'name' => 'Stephany da Costa',
            'cpf' => '076.539.812-59',
            'cnpj' => '',
            'phone' => '+55 21 5115 0552',
            'cep' => '35192303',
            'address' => 'Viela de Costa',
            'address_number' => '5',
            'state' => 'MS',
            'city' => 'Dias',
        ],
        [
            'type' => 'PJ',
            'name' => 'da Mata Ramos S/A',
            'cpf' => '',
            'cnpj' => '75.410.629/0001-09',
            'phone' => '(071) 4485-2911',
            'cep' => '26223-583',
            'address' => 'Estação Gonçalves',
            'address_number' => '16',
            'state' => 'BA',
            'city' => 'Novaes',
        ],
        [
            'type' => 'PF',
            'name' => 'Samuel Cardoso',
            'cpf' => '264.731.589-28',
            'cnpj' => '',
            'phone' => '+55 21 3758 0660',
            'cep' => '57354-712',
            'address' => 'Ladeira Correia',
            'address_number' => '892',
            'state' => 'MG',
            'city' => 'Peixoto',
        ],
        [
            'type' => 'PF',
            'name' => 'Camila Farias',
            'cpf' => '752.930.841-60',
            'cnpj' => '',
            'phone' => '+55 (011) 7970 3414',
            'cep' => '67173864',
            'address' => 'Alameda de Costa',
            'address_number' => '10',
            'state' => 'GO',
            'city' => 'Souza Verde',
        ],
        [
            'type' => 'PJ',
            'name' => 'Pires',
            'cpf' => '',
            'cnpj' => '14.527.903/0001-30',
            'phone' => '+55 11 4485 1832',
            'cep' => '64482983',
            'address' => 'Colônia de Oliveira',
            'address_number' => '564',
            'state' => 'PB',
            'city' => 'Cunha da Serra',
        ],
        [
            'type' => 'PJ',
            'name' => 'Costa - ME',
            'cpf' => '',
            'cnpj' => '67.245.893/0001-06',
            'phone' => '(071) 6377-8570',
            'cep' => '42709-305',
            'address' => 'Passarela Anthony Souza',
            'address_number' => '2',
            'state' => 'RO',
            'city' => 'Almeida da Praia',
        ],
        [
            'type' => 'PF',
            'name' => 'Carlos Eduardo Almeida',
            'cpf' => '493.182.607-50',
            'cnpj' => '',
            'phone' => '(051) 5625-6627',
            'cep' => '85232756',
            'address' => 'Residencial Yago das Neves',
            'address_number' => '47',
            'state' => 'RJ',
            'city' => 'Nogueira',
        ],
        [
            'type' => 'PJ',
            'name' => 'Dias e Filhos',
            'cpf' => '',
            'cnpj' => '12.507.948/0001-17',
            'phone' => '(031) 9184 5670',
            'cep' => '97747-354',
            'address' => 'Área Barros',
            'address_number' => '15',
            'state' => 'MA',
            'city' => 'Cunha',
        ],
        [
            'type' => 'PJ',
            'name' => 'Pereira e Filhos',
            'cpf' => '',
            'cnpj' => '36.971.204/0001-17',
            'phone' => '+55 21 5587 5408',
            'cep' => '35138533',
            'address' => 'Viela Natália Jesus',
            'address_number' => '78',
            'state' => 'GO',
            'city' => 'Monteiro de Duarte',
        ],
        [
            'type' => 'PJ',
            'name' => 'Lima - EI',
            'cpf' => '',
            'cnpj' => '10.735.689/0001-56',
            'phone' => '11 7711-1312',
            'cep' => '37916-860',
            'address' => 'Feira Rodrigues',
            'address_number' => '52',
            'state' => 'MS',
            'city' => 'Pinto do Campo',
        ],
        [
            'type' => 'PF',
            'name' => 'Esther Viana',
            'cpf' => '347.869.210-50',
            'cnpj' => '',
            'phone' => '+55 (031) 1912 6334',
            'cep' => '88601641',
            'address' => 'Travessa de Moraes',
            'address_number' => '58',
            'state' => 'ES',
            'city' => 'Campos',
        ],
        [
            'type' => 'PJ',
            'name' => 'Martins',
            'cpf' => '',
            'cnpj' => '35.724.180/0001-39',
            'phone' => '81 8559-0262',
            'cep' => '81237933',
            'address' => 'Conjunto de Dias',
            'address_number' => '35',
            'state' => 'RS',
            'city' => 'Cavalcanti de Araújo',
        ],
        [
            'type' => 'PJ',
            'name' => 'Rodrigues',
            'cpf' => '',
            'cnpj' => '74.018.632/0001-19',
            'phone' => '(081) 8514-2963',
            'cep' => '46030-535',
            'address' => 'Viaduto Mirella das Neves',
            'address_number' => '35',
            'state' => 'MA',
            'city' => 'Moraes',
        ],
        [
            'type' => 'PJ',
            'name' => 'da Costa Ltda.',
            'cpf' => '',
            'cnpj' => '07.981.643/0001-02',
            'phone' => '(061) 1056 2376',
            'cep' => '54256606',
            'address' => 'Setor Emilly Rezende',
            'address_number' => '2',
            'state' => 'PA',
            'city' => 'da Cunha do Sul',
        ],
        [
            'type' => 'PF',
            'name' => 'Beatriz Silva',
            'cpf' => '215.867.039-86',
            'cnpj' => '',
            'phone' => '+55 21 6919 7299',
            'cep' => '45600715',
            'address' => 'Viaduto Heitor Ramos',
            'address_number' => '68',
            'state' => 'CE',
            'city' => 'Mendes Paulista',
        ],
        [
            'type' => 'PF',
            'name' => 'Julia Alves',
            'cpf' => '489.730.256-00',
            'cnpj' => '',
            'phone' => '(051) 6165-7004',
            'cep' => '49438856',
            'address' => 'Favela Enzo Melo',
            'address_number' => '99',
            'state' => 'RO',
            'city' => 'da Cruz Grande',
        ],
        [
            'type' => 'PF',
            'name' => 'Sr. Nathan Barros',
            'cpf' => '925.867.413-82',
            'cnpj' => '',
            'phone' => '0300-620-2907',
            'cep' => '50749318',
            'address' => 'Ladeira João Felipe Souza',
            'address_number' => '31',
            'state' => 'RJ',
            'city' => 'Santos',
        ],
        [
            'type' => 'PJ',
            'name' => 'Pinto',
            'cpf' => '',
            'cnpj' => '49.803.275/0001-52',
            'phone' => '51 8553 6208',
            'cep' => '96570869',
            'address' => 'Alameda Moreira',
            'address_number' => '623',
            'state' => 'RS',
            'city' => 'Aragão de Farias',
        ],
        [
            'type' => 'PF',
            'name' => 'Eduarda Freitas',
            'cpf' => '261.437.590-06',
            'cnpj' => '',
            'phone' => '+55 (071) 2716-6446',
            'cep' => '95140-704',
            'address' => 'Passarela Nogueira',
            'address_number' => '16',
            'state' => 'RJ',
            'city' => 'Moraes de Costela',
        ],
        [
            'type' => 'PJ',
            'name' => 'Martins',
            'cpf' => '',
            'cnpj' => '06.741.982/0001-59',
            'phone' => '(084) 5013 1870',
            'cep' => '05624-629',
            'address' => 'Passarela Lima',
            'address_number' => '302',
            'state' => 'BA',
            'city' => 'Barbosa de Silveira',
        ],
        [
            'type' => 'PJ',
            'name' => 'Nogueira S.A.',
            'cpf' => '',
            'cnpj' => '51.847.293/0001-88',
            'phone' => '(061) 4487 2782',
            'cep' => '92805137',
            'address' => 'Feira de Ramos',
            'address_number' => '325',
            'state' => 'PR',
            'city' => 'Viana',
        ],
        [
            'type' => 'PF',
            'name' => 'Luiz Henrique Mendes',
            'cpf' => '018.342.675-44',
            'cnpj' => '',
            'phone' => '31 5125-0220',
            'cep' => '93060-460',
            'address' => 'Esplanada de Moraes',
            'address_number' => '7',
            'state' => 'AL',
            'city' => 'Moraes de Fernandes',
        ],
        [
            'type' => 'PJ',
            'name' => 'Ramos',
            'cpf' => '',
            'cnpj' => '62.038.197/0001-05',
            'phone' => '11 1105 0269',
            'cep' => '57877108',
            'address' => 'Jardim Benício Silveira',
            'address_number' => '2',
            'state' => 'MT',
            'city' => 'Castro do Amparo',
        ],
        [
            'type' => 'PF',
            'name' => 'Davi Lucas Silveira',
            'cpf' => '408.321.975-05',
            'cnpj' => '',
            'phone' => '+55 (031) 3950-7603',
            'cep' => '45235326',
            'address' => 'Núcleo Heloísa Cunha',
            'address_number' => '19',
            'state' => 'CE',
            'city' => 'Nogueira',
        ],
        [
            'type' => 'PF',
            'name' => 'Srta. Brenda Aragão',
            'cpf' => '059.768.143-01',
            'cnpj' => '',
            'phone' => '+55 (041) 6695 3258',
            'cep' => '86126951',
            'address' => 'Praça Luigi Ribeiro',
            'address_number' => '73',
            'state' => 'ES',
            'city' => 'Novaes de Campos',
        ],
        [
            'type' => 'PF',
            'name' => 'Guilherme Souza',
            'cpf' => '580.463.197-75',
            'cnpj' => '',
            'phone' => '0800-561-8026',
            'cep' => '66617972',
            'address' => 'Loteamento Ribeiro',
            'address_number' => '52',
            'state' => 'SP',
            'city' => 'Moura',
        ],
        [
            'type' => 'PF',
            'name' => 'Sr. Pedro Lucas Moraes',
            'cpf' => '780.126.543-26',
            'cnpj' => '',
            'phone' => '+55 (061) 4860 6463',
            'cep' => '22195-206',
            'address' => 'Passarela de Rezende',
            'address_number' => '2',
            'state' => 'SP',
            'city' => 'Viana da Prata',
        ],
        [
            'type' => 'PF',
            'name' => 'Davi Luiz da Costa',
            'cpf' => '329.041.758-14',
            'cnpj' => '',
            'phone' => '(071) 1642 5858',
            'cep' => '68436567',
            'address' => 'Lagoa de Oliveira',
            'address_number' => '31',
            'state' => 'BA',
            'city' => 'Silveira',
        ],
        [
            'type' => 'PJ',
            'name' => 'da Rocha - EI',
            'cpf' => '',
            'cnpj' => '98.125.473/0001-10',
            'phone' => '+55 21 0015 7517',
            'cep' => '94732-881',
            'address' => 'Esplanada de Araújo',
            'address_number' => '78',
            'state' => 'RN',
            'city' => 'Pires',
        ],
        [
            'type' => 'PF',
            'name' => 'Dra. Juliana Ferreira',
            'cpf' => '026.134.975-99',
            'cnpj' => '',
            'phone' => '0900 653 8707',
            'cep' => '48786742',
            'address' => 'Setor Moreira',
            'address_number' => '34',
            'state' => 'PB',
            'city' => 'Campos',
        ],
        [
            'type' => 'PF',
            'name' => 'Julia Oliveira',
            'cpf' => '814.390.275-79',
            'cnpj' => '',
            'phone' => '+55 41 2029 8300',
            'cep' => '89717-855',
            'address' => 'Viela Almeida',
            'address_number' => '83',
            'state' => 'TO',
            'city' => 'Freitas de Goiás',
        ],
        [
            'type' => 'PJ',
            'name' => 'Sales Ltda.',
            'cpf' => '',
            'cnpj' => '85.102.436/0001-44',
            'phone' => '31 6234 3754',
            'cep' => '92165-873',
            'address' => 'Núcleo de Moraes',
            'address_number' => '64',
            'state' => 'MG',
            'city' => 'Cavalcanti do Amparo',
        ],
        [
            'type' => 'PJ',
            'name' => 'Costa',
            'cpf' => '',
            'cnpj' => '72.519.684/0001-43',
            'phone' => '+55 31 1667-8799',
            'cep' => '68473580',
            'address' => 'Recanto Lopes',
            'address_number' => '73',
            'state' => 'AL',
            'city' => 'Oliveira',
        ],
        [
            'type' => 'PF',
            'name' => 'Francisco da Paz',
            'cpf' => '521.798.034-60',
            'cnpj' => '',
            'phone' => '+55 (021) 6802 1993',
            'cep' => '73089618',
            'address' => 'Fazenda Dias',
            'address_number' => '86',
            'state' => 'SE',
            'city' => 'Pinto',
        ],
        [
            'type' => 'PJ',
            'name' => 'Nascimento Barbosa - EI',
            'cpf' => '',
            'cnpj' => '40.572.639/0001-66',
            'phone' => '+55 84 9814 1140',
            'cep' => '92639536',
            'address' => 'Rodovia de Costa',
            'address_number' => '217',
            'state' => 'PE',
            'city' => 'Ribeiro de da Luz',
        ],
        [
            'type' => 'PJ',
            'name' => 'Vieira',
            'cpf' => '',
            'cnpj' => '52.683.074/0001-73',
            'phone' => '(051) 3576-0708',
            'cep' => '73634-772',
            'address' => 'Praia Gomes',
            'address_number' => '37',
            'state' => 'TO',
            'city' => 'da Mota',
        ],
        [
            'type' => 'PF',
            'name' => 'Luiz Henrique Costa',
            'cpf' => '025.984.137-41',
            'cnpj' => '',
            'phone' => '+55 (071) 6732-6058',
            'cep' => '52889962',
            'address' => 'Vila de Sales',
            'address_number' => '839',
            'state' => 'AL',
            'city' => 'Rodrigues',
        ],
        [
            'type' => 'PJ',
            'name' => 'da Paz',
            'cpf' => '',
            'cnpj' => '09.816.352/0001-94',
            'phone' => '+55 51 8645 7325',
            'cep' => '76757-123',
            'address' => 'Distrito Novaes',
            'address_number' => '48',
            'state' => 'MS',
            'city' => 'Aragão',
        ],
        [
            'type' => 'PF',
            'name' => 'Cecília Carvalho',
            'cpf' => '693.501.742-43',
            'cnpj' => '',
            'phone' => '71 8119-7036',
            'cep' => '41039-098',
            'address' => 'Distrito Bianca Ferreira',
            'address_number' => '8',
            'state' => 'GO',
            'city' => 'Nascimento',
        ],
        [
            'type' => 'PJ',
            'name' => 'Santos',
            'cpf' => '',
            'cnpj' => '53.406.128/0001-16',
            'phone' => '0800 971 8765',
            'cep' => '01692-201',
            'address' => 'Praça de Farias',
            'address_number' => '5',
            'state' => 'GO',
            'city' => 'Correia da Praia',
        ],
        [
            'type' => 'PJ',
            'name' => 'Moura',
            'cpf' => '',
            'cnpj' => '93.024.578/0001-69',
            'phone' => '11 0452-5198',
            'cep' => '14918-192',
            'address' => 'Área Eloah das Neves',
            'address_number' => '91',
            'state' => 'TO',
            'city' => 'da Luz',
        ],
        [
            'type' => 'PF',
            'name' => 'Dra. Daniela Nunes',
            'cpf' => '375.128.609-86',
            'cnpj' => '',
            'phone' => '(051) 2480 1545',
            'cep' => '19041243',
            'address' => 'Sítio de Monteiro',
            'address_number' => '71',
            'state' => 'PE',
            'city' => 'Costa de Minas',
        ],
        [
            'type' => 'PJ',
            'name' => 'Martins',
            'cpf' => '',
            'cnpj' => '24.357.906/0001-26',
            'phone' => '+55 (021) 4155 8403',
            'cep' => '49066493',
            'address' => 'Largo Emilly Rodrigues',
            'address_number' => '71',
            'state' => 'MS',
            'city' => 'Silveira',
        ],
        [
            'type' => 'PJ',
            'name' => 'Dias e Filhos',
            'cpf' => '',
            'cnpj' => '76.019.253/0001-79',
            'phone' => '+55 81 7058 6183',
            'cep' => '44667-028',
            'address' => 'Estrada Luiz Felipe da Costa',
            'address_number' => '34',
            'state' => 'CE',
            'city' => 'Viana do Sul',
        ],
        [
            'type' => 'PF',
            'name' => 'Enzo Peixoto',
            'cpf' => '239.641.578-64',
            'cnpj' => '',
            'phone' => '+55 (031) 7306 2686',
            'cep' => '68871218',
            'address' => 'Chácara Alves',
            'address_number' => '86',
            'state' => 'RO',
            'city' => 'Oliveira da Praia',
        ],
        [
            'type' => 'PJ',
            'name' => 'Ferreira',
            'cpf' => '',
            'cnpj' => '12.359.048/0001-70',
            'phone' => '+55 (084) 7372 9840',
            'cep' => '55548420',
            'address' => 'Estrada Lara Novaes',
            'address_number' => '57',
            'state' => 'PB',
            'city' => 'Ribeiro',
        ],
        [
            'type' => 'PF',
            'name' => 'Samuel Melo',
            'cpf' => '568.437.290-29',
            'cnpj' => '',
            'phone' => '+55 (071) 6348-2829',
            'cep' => '54647-803',
            'address' => 'Quadra Maria Sophia Campos',
            'address_number' => '4',
            'state' => 'RN',
            'city' => 'Fernandes',
        ],
        [
            'type' => 'PF',
            'name' => 'Enrico da Mata',
            'cpf' => '925.480.637-47',
            'cnpj' => '',
            'phone' => '(041) 3675 5196',
            'cep' => '02098453',
            'address' => 'Estrada Pedro Miguel da Mata',
            'address_number' => '37',
            'state' => 'RN',
            'city' => 'Dias do Sul',
        ],
        [
            'type' => 'PF',
            'name' => 'Leandro Azevedo',
            'cpf' => '281.395.740-23',
            'cnpj' => '',
            'phone' => '(081) 2547 7954',
            'cep' => '72184869',
            'address' => 'Pátio Maria Clara da Cruz',
            'address_number' => '262',
            'state' => 'RJ',
            'city' => 'da Mata',
        ],
        [
            'type' => 'PF',
            'name' => 'Sra. Evelyn Castro',
            'cpf' => '648.902.537-00',
            'cnpj' => '',
            'phone' => '0500-021-6670',
            'cep' => '21693-036',
            'address' => 'Avenida Nunes',
            'address_number' => '58',
            'state' => 'PA',
            'city' => 'Viana do Norte',
        ],
        [
            'type' => 'PJ',
            'name' => 'Viana',
            'cpf' => '',
            'cnpj' => '28.951.460/0001-14',
            'phone' => '0500 744 4360',
            'cep' => '81042282',
            'address' => 'Loteamento Almeida',
            'address_number' => '62',
            'state' => 'RJ',
            'city' => 'Carvalho',
        ],
        [
            'type' => 'PJ',
            'name' => 'da Rocha',
            'cpf' => '',
            'cnpj' => '47.583.609/0001-02',
            'phone' => '(051) 7668 7868',
            'cep' => '32685212',
            'address' => 'Área Nogueira',
            'address_number' => '911',
            'state' => 'GO',
            'city' => 'Moraes do Amparo',
        ],
        [
            'type' => 'PF',
            'name' => 'Maria Sophia Lopes',
            'cpf' => '975.140.362-61',
            'cnpj' => '',
            'phone' => '31 0391-7156',
            'cep' => '80881095',
            'address' => 'Núcleo da Mata',
            'address_number' => '84',
            'state' => 'PR',
            'city' => 'Almeida de Goiás',
        ],
        [
            'type' => 'PF',
            'name' => 'Milena Rocha',
            'cpf' => '520.693.148-98',
            'cnpj' => '',
            'phone' => '0800 730 7992',
            'cep' => '59569-286',
            'address' => 'Feira Vicente Nascimento',
            'address_number' => '43',
            'state' => 'GO',
            'city' => 'Teixeira',
        ],
        [
            'type' => 'PF',
            'name' => 'Isadora Ramos',
            'cpf' => '352.718.690-59',
            'cnpj' => '',
            'phone' => '61 9177-3295',
            'cep' => '18734648',
            'address' => 'Morro Oliveira',
            'address_number' => '10',
            'state' => 'DF',
            'city' => 'da Cruz',
        ],
        [
            'type' => 'PF',
            'name' => 'Laís Cardoso',
            'cpf' => '489.536.271-09',
            'cnpj' => '',
            'phone' => '+55 (071) 1052 4987',
            'cep' => '86753-111',
            'address' => 'Alameda de Silva',
            'address_number' => '29',
            'state' => 'RJ',
            'city' => 'Aragão',
        ],
        [
            'type' => 'PF',
            'name' => 'Yuri Castro',
            'cpf' => '416.589.732-91',
            'cnpj' => '',
            'phone' => '+55 (031) 2932-2347',
            'cep' => '29431-262',
            'address' => 'Trecho Aragão',
            'address_number' => '88',
            'state' => 'RO',
            'city' => 'Fogaça',
        ],
        [
            'type' => 'PF',
            'name' => 'Thiago Freitas',
            'cpf' => '930.164.758-39',
            'cnpj' => '',
            'phone' => '+55 (011) 7808-5327',
            'cep' => '73431-574',
            'address' => 'Setor Joana Gomes',
            'address_number' => '94',
            'state' => 'MG',
            'city' => 'da Luz',
        ],
        [
            'type' => 'PJ',
            'name' => 'Correia',
            'cpf' => '',
            'cnpj' => '91.253.864/0001-70',
            'phone' => '61 3214-7568',
            'cep' => '56682892',
            'address' => 'Área de Lima',
            'address_number' => '778',
            'state' => 'DF',
            'city' => 'da Rocha de Novaes',
        ],
        [
            'type' => 'PJ',
            'name' => 'Castro - EI',
            'cpf' => '',
            'cnpj' => '61.759.803/0001-19',
            'phone' => '+55 31 3196-6183',
            'cep' => '37131829',
            'address' => 'Sítio Silveira',
            'address_number' => '769',
            'state' => 'RS',
            'city' => 'Ribeiro do Sul',
        ],
        [
            'type' => 'PF',
            'name' => 'Dr. Vitor da Rocha',
            'cpf' => '037.146.982-13',
            'cnpj' => '',
            'phone' => '(051) 7194-4654',
            'cep' => '91759913',
            'address' => 'Pátio Duarte',
            'address_number' => '8',
            'state' => 'MA',
            'city' => 'Silveira',
        ],
        [
            'type' => 'PF',
            'name' => 'Isadora da Conceição',
            'cpf' => '185.270.643-08',
            'cnpj' => '',
            'phone' => '(021) 8666 0271',
            'cep' => '28397-529',
            'address' => 'Travessa Pereira',
            'address_number' => '23',
            'state' => 'CE',
            'city' => 'Pires',
        ],
        [
            'type' => 'PJ',
            'name' => 'da Luz',
            'cpf' => '',
            'cnpj' => '04.789.253/0001-47',
            'phone' => '11 3800-9174',
            'cep' => '86231-982',
            'address' => 'Via Letícia Farias',
            'address_number' => '4',
            'state' => 'BA',
            'city' => 'da Costa',
        ],
        [
            'type' => 'PJ',
            'name' => 'Campos Cavalcanti Ltda.',
            'cpf' => '',
            'cnpj' => '14.782.630/0001-70',
            'phone' => '+55 11 2705 5466',
            'cep' => '43319238',
            'address' => 'Praia Lopes',
            'address_number' => '5',
            'state' => 'PA',
            'city' => 'Melo',
        ],
        [
            'type' => 'PJ',
            'name' => 'da Paz',
            'cpf' => '',
            'cnpj' => '41.756.289/0001-50',
            'phone' => '+55 71 4152-7067',
            'cep' => '48967998',
            'address' => 'Esplanada Almeida',
            'address_number' => '71',
            'state' => 'RR',
            'city' => 'da Paz do Amparo',
        ],
        [
            'type' => 'PJ',
            'name' => 'Ferreira',
            'cpf' => '',
            'cnpj' => '86.243.719/0001-79',
            'phone' => '+55 (021) 3541 0645',
            'cep' => '56213577',
            'address' => 'Viela Moraes',
            'address_number' => '76',
            'state' => 'MS',
            'city' => 'Carvalho',
        ],
        [
            'type' => 'PJ',
            'name' => 'Costela',
            'cpf' => '',
            'cnpj' => '10.653.972/0001-39',
            'phone' => '+55 41 6049 2448',
            'cep' => '85020155',
            'address' => 'Estrada Luigi Moura',
            'address_number' => '974',
            'state' => 'CE',
            'city' => 'Nunes de Alves',
        ],
        [
            'type' => 'PF',
            'name' => 'Alexandre Cavalcanti',
            'cpf' => '534.706.298-38',
            'cnpj' => '',
            'phone' => '71 9403-1272',
            'cep' => '74279086',
            'address' => 'Condomínio Castro',
            'address_number' => '71',
            'state' => 'DF',
            'city' => 'Nogueira de Goiás',
        ],
        [
            'type' => 'PJ',
            'name' => 'Santos',
            'cpf' => '',
            'cnpj' => '85.239.067/0001-36',
            'phone' => '+55 31 4585-7745',
            'cep' => '22375-057',
            'address' => 'Vila de Gomes',
            'address_number' => '20',
            'state' => 'PB',
            'city' => 'da Paz',
        ],
        [
            'type' => 'PF',
            'name' => 'Pietra Melo',
            'cpf' => '820.365.417-71',
            'cnpj' => '',
            'phone' => '+55 (081) 9317-2188',
            'cep' => '94316-087',
            'address' => 'Loteamento de Almeida',
            'address_number' => '59',
            'state' => 'TO',
            'city' => 'Porto do Galho',
        ],
        [
            'type' => 'PJ',
            'name' => 'Campos',
            'cpf' => '',
            'cnpj' => '01.537.642/0001-97',
            'phone' => '+55 31 4768-0647',
            'cep' => '66699478',
            'address' => 'Lagoa Ana Beatriz da Cunha',
            'address_number' => '70',
            'state' => 'PB',
            'city' => 'Lima de Campos',
        ],
        [
            'type' => 'PJ',
            'name' => 'Melo Dias - ME',
            'cpf' => '',
            'cnpj' => '05.213.948/0001-49',
            'phone' => '0500-032-0866',
            'cep' => '46748027',
            'address' => 'Colônia Correia',
            'address_number' => '54',
            'state' => 'MA',
            'city' => 'Azevedo Verde',
        ],
        [
            'type' => 'PF',
            'name' => 'Isaac Rezende',
            'cpf' => '104.932.658-05',
            'cnpj' => '',
            'phone' => '(011) 0015-0440',
            'cep' => '09029271',
            'address' => 'Conjunto de Aragão',
            'address_number' => '221',
            'state' => 'RR',
            'city' => 'Correia',
        ],
        [
            'type' => 'PF',
            'name' => 'Caio Rodrigues',
            'cpf' => '618.359.720-12',
            'cnpj' => '',
            'phone' => '+55 84 5682 1808',
            'cep' => '16585898',
            'address' => 'Lagoa Lucca Carvalho',
            'address_number' => '79',
            'state' => 'SP',
            'city' => 'Gomes da Praia',
        ],
        [
            'type' => 'PF',
            'name' => 'Isadora Aragão',
            'cpf' => '092.751.486-94',
            'cnpj' => '',
            'phone' => '(084) 7244-2025',
            'cep' => '31872-453',
            'address' => 'Condomínio de Farias',
            'address_number' => '26',
            'state' => 'GO',
            'city' => 'Moraes do Norte',
        ],
        [
            'type' => 'PJ',
            'name' => 'Dias',
            'cpf' => '',
            'cnpj' => '60.942.158/0001-02',
            'phone' => '+55 81 1560-4324',
            'cep' => '81273-999',
            'address' => 'Pátio Gomes',
            'address_number' => '5',
            'state' => 'AC',
            'city' => 'da Cruz',
        ],
        [
            'type' => 'PF',
            'name' => 'Sr. João Dias',
            'cpf' => '983.054.172-04',
            'cnpj' => '',
            'phone' => '0900 955 5106',
            'cep' => '27369-039',
            'address' => 'Residencial de Oliveira',
            'address_number' => '32',
            'state' => 'RO',
            'city' => 'Nascimento dos Dourados',
        ],
        [
            'type' => 'PF',
            'name' => 'Dra. Melissa da Rosa',
            'cpf' => '412.907.856-94',
            'cnpj' => '',
            'phone' => '+55 61 2648-6586',
            'cep' => '71495-444',
            'address' => 'Trevo Eduarda Aragão',
            'address_number' => '98',
            'state' => 'DF',
            'city' => 'Fogaça das Pedras',
        ],
        [
            'type' => 'PJ',
            'name' => 'Aragão - ME',
            'cpf' => '',
            'cnpj' => '81.450.632/0001-59',
            'phone' => '51 8587 8787',
            'cep' => '90953461',
            'address' => 'Colônia da Cunha',
            'address_number' => '872',
            'state' => 'MT',
            'city' => 'da Costa de Rodrigues',
        ],
        [
            'type' => 'PF',
            'name' => 'Luigi Mendes',
            'cpf' => '830.246.957-29',
            'cnpj' => '',
            'phone' => '(041) 2822 1530',
            'cep' => '77198027',
            'address' => 'Conjunto de Ferreira',
            'address_number' => '5',
            'state' => 'MS',
            'city' => 'Rezende',
        ],
        [
            'type' => 'PJ',
            'name' => 'Barbosa',
            'cpf' => '',
            'cnpj' => '51.849.023/0001-06',
            'phone' => '(041) 9520 7663',
            'cep' => '64767626',
            'address' => 'Praça da Mota',
            'address_number' => '31',
            'state' => 'PB',
            'city' => 'Moreira da Mata',
        ],
        [
            'type' => 'PJ',
            'name' => 'Mendes',
            'cpf' => '',
            'cnpj' => '32.715.869/0001-09',
            'phone' => '+55 (021) 1899-7521',
            'cep' => '24511-655',
            'address' => 'Loteamento Sarah Almeida',
            'address_number' => '34',
            'state' => 'CE',
            'city' => 'Ribeiro',
        ],
        [
            'type' => 'PF',
            'name' => 'Bruno Souza',
            'cpf' => '410.357.682-08',
            'cnpj' => '',
            'phone' => '+55 (011) 2012-1691',
            'cep' => '19913-462',
            'address' => 'Praia de Fogaça',
            'address_number' => '72',
            'state' => 'GO',
            'city' => 'da Cruz',
        ],
        [
            'type' => 'PF',
            'name' => 'Srta. Clara Silveira',
            'cpf' => '571.243.680-90',
            'cnpj' => '',
            'phone' => '+55 84 5273 3127',
            'cep' => '15315-233',
            'address' => 'Sítio de Lopes',
            'address_number' => '85',
            'state' => 'PE',
            'city' => 'Gonçalves do Sul',
        ],
        [
            'type' => 'PF',
            'name' => 'Nina da Mata',
            'cpf' => '431.287.059-41',
            'cnpj' => '',
            'phone' => '51 8899 8665',
            'cep' => '35728-072',
            'address' => 'Chácara Aragão',
            'address_number' => '11',
            'state' => 'MT',
            'city' => 'da Mota de Minas',
        ],
    ];
}
